# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Test
  jobs:
    - job: A1
      steps:
      - bash: echo "Hello world"


- stage: Build
  jobs:
    - job: A2
      steps:
      - bash: echo "Hello world"

- stage: Deploy
  dependsOn: Build
  jobs:
    - job: A3
      steps:
      - bash: echo "Hello world"



    





