stages:
  - stage: build_stage
    dependsOn: []
    pool:
      vmimage: ubuntu-20.04
    displayName:  Build Stage
    jobs:
      - job: Build
        steps:
          - script: |
              echo "Build working"
            displayName: Build 
  - stage: Build_stage_connpack
    dependsOn: []
    pool:
      vmimage: ubuntu-20.04
    displayName: Build Stage connpack
    jobs:
      - job: Build_stage
        steps:
          - script: |
              echo "Build ConnPack"
            displayName: Build Connpack

  - stage: Testing
    dependsOn:
      - Build_stage_connpack
      - build_stage
    pool:
      vmimage: ubuntu-20.04
    displayName: Testing
    jobs:
      - job: Tests
        steps:
          - script: |
              echo "Testing"
            displayName:  Testing
